apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.100-10.1.1.110 # The user will need to update this line with a bank of IP addresses that will work in their envrionment.