#NGINX NIC OSS caching
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juiceshop-vs
  namespace: juice
spec:
  http-snippets: |
    proxy_cache_path /tmp levels=1:2 keys_zone=juiceshop:10m max_size=256m;
    add_header X-Cache-Status $upstream_cache_status;
  host: juiceshop.example.com
  tls:
    secret: juice-secret
  upstreams:
  - name: juiceshop
    service: juiceshop-svc
    port: 80
    lb-method: least_conn
    #slow-start: 10s
    #healthCheck:
      #port: 3000
      #enable: true
      #path: /
      #interval: 20s
      #jitter: 3s
      #fails: 3
      #passes: 2
      #port: 3000
      #connect-timeout: 20s
      #read-timeout: 20s
  routes:
  - path: ~*\\.css|js|jpg|png
    location-snippets: |
      proxy_cache juiceshop;
      proxy_cache_valid 200 30s;
      proxy_cache_methods GET;
      proxy_ignore_headers Cache-Control;
    action:
      pass: juiceshop
  - path: /
    action:
      pass: juiceshop