# NLK Nodeport Service file
# NodePort -ports name must be in the format of
### nlk-<upstream-block-name>
# The nginxinc.io Annotation must be added
# Add ports 6379 and 6380 for Redis
# Chris Akker, Jan 2024
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    nginxinc.io/nlk-nginx-lb-http: "stream"    # Must be added
    nginxinc.io/nlk-nginx-lb-https: "stream"   # Must be added
    nginxinc.io/nlk-cluster1-redis-leader: "stream"   # Must be added
    nginxinc.io/nlk-cluster1-redis-follower: "stream"   # Must be added
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nlk-nginx-lb-http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: nlk-nginx-lb-https
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: nlk-cluster1-redis-leader
  - port: 6380
    targetPort: 6380
    protocol: TCP
    name: nlk-cluster1-redis-follower
  selector:
    app: nginx-ingress
    
