# NIC LoadBalancer Service file, adding Redis
# externalIPs are set to Nginx LB Server
# Add ports 6379 and 6380 for Redis
# Chris Akker, Apr 2024 
#
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  externalIPs:
  - 10.1.1.4          #Nginx LB1 Server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis-leader
  - port: 6380
    targetPort: 6380
    protocol: TCP
    name: redis-follower
  selector:
    app: nginx-ingress
