#Example virtual server with routes for Juiceshop Demo
#
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juiceshop-vs
  namespace: juice
spec:
  host: juiceshop.example.com
  tls:
    secret: juice-secret
  upstreams:
  - name: juiceshop
    service: juiceshop-svc
    port: 80
    slow-start: 5s
    healthCheck:
      enable: true
      port: 3000
      path: /
      interval: 20s
      jitter: 3s
      fails: 3
      passes: 1
      connect-timeout: 30s
      read-timeout: 30s
  routes:
  - path: /
    action:
      pass: juiceshop
